apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: challenge
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: wiz-db:local # docker build -t wiz-db:local ./db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: ctfapp
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: postgres-credentials, key: POSTGRES_PASSWORD }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: checkpoint7-flag
              mountPath: /etc/secrets/checkpoint7-flag
              subPath: checkpoint7-flag
              readOnly: true
      volumes:
        - name: checkpoint7-flag
          secret: { secretName: checkpoint7-flag }
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: { storage: 1Gi }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: challenge
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
