apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-store
  namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels: { app: credential-store }
  template:
    metadata:
      labels: { app: credential-store }
    spec:
      automountServiceAccountToken: false
      containers:
        - name: credential-store
          image: wiz-credential-store:local # docker build -t wiz-credential-store:local ./credential-store
          ports:
            - containerPort: 8080
          env:
            - name: CREDENTIAL_STORE_PEPPER
              value: wiznt-onboarding-pepper-2024
          volumeMounts:
            - name: service-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: service-token
          secret:
            secretName: service-token
            items:
              - key: token
                path: token
---
apiVersion: v1
kind: Service
metadata:
  name: credential-store
  namespace: challenge
spec:
  selector: { app: credential-store }
  ports:
    - port: 8080
      targetPort: 8080
